import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../build.css"

import Header from "@/components/header";
import Footer from "@/components/footer";
import { Providers } from "@/components/common/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

          <div className="bg-white">
            <Header></Header>
            {children}
            <Footer></Footer>
          </div>

      </body>
    </html>
  );
}
